### ISSUE TITLE
ArgumentException at LXHttpClinet when trying to open a connection

### ISSUE THREAD

**Issue by mabiste** [manison/Loxone.NET#3]
Hello,

based on the console sample program from token-authentication branch I'm trying to open a connection to my local miniserver using a miniserver address like "http://192.168.1.100/".

But I get a ArgumentException, the message:
> ArgumentException: Es sind nur HTTP- und HTTPS-Schemas zulässig.
> Parametername: value

The exception occurs at LXHttpClient#EnsureHttpClient(). Here is the (truncated call stack):

> System.AggregateException
>   HResult=0x80131500
>   Message=Mindestens ein Fehler ist aufgetreten.
>   Source=Loxone.NET.Test
>   StackTrace:
>    at Loxone.NET.Test.Program.Main(String[] args)
> 
>   This exception was originally thrown at this call stack:
> 	System.Net.Http.HttpClient.CheckBaseAddress(System.Uri, string)
> 	System.Net.Http.HttpClient.BaseAddress.set(System.Uri)
>     Loxone.Client.Transport.LXHttpClient.EnsureHttpClient() in LXHttpClient.cs
>     Loxone.Client.Transport.LXHttpClient.RequestCommandInternalAsync<T>(string, Loxone.Client.CommandEncryption, System.Threading.CancellationToken) in LXHttpClient.cs
> 	System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
> 	System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
> 	System.Runtime.CompilerServices.ConfiguredTaskAwaitable<TResult>.ConfiguredTaskAwaiter.GetResult()
>     Loxone.Client.Transport.LXClient.RequestCommandAsync<T>(string, Loxone.Client.CommandEncryption, Loxone.Client.Transport.LXClient.RequestCommandValidation, System.Threading.CancellationToken) in LXClient.cs
> 	System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
> 	System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
>     ...
>     [Call Stack Truncated]
> Inner Exception 1:
> ArgumentException: Es sind nur HTTP- und HTTPS-Schemas zulässig.
> Parametername: value

While debugged, I've seen a wrong base url scheme ('ws'), but it was correctly set before:
![Ashampoo_Snap_Samstag, 4  Januar 2020_18h59m21s_001_](https://user-images.githubusercontent.com/5878397/71769698-82eb2c80-2f24-11ea-95ef-fe1da9d9172f.png)

Anyone here can help me? Thanks!
Marco

**Comment by manison** [comment]
Now rebased into master.

**Comment by mabiste** [comment]
It's working now, thank you very much! :-)
